spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: 127.0.0.1
server:
  port: 8080
security:
  oauth2:
    resource:
      filter-order: 3